version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.3
    environment:
      - DSN=postgres://kratos:kratos@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:kratos@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  # kratos-selfservice-ui-node:
  #   image: kratos-selfservice-ui
  #   environment:
  #     - KRATOS_PUBLIC_URL=http://kratos:4433/
  #     - KRATOS_ADMIN_URL=http://kratos:4434/
  #   networks:
  #     - intranet
  #   restart: on-failure

  hydra:
    image: oryd/hydra:v1.11.8
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      -
        type: bind
        source: ./hydra
        target: /etc/config/hydra
    environment:
      - DSN=postgres://hydra:hydra@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.11.8
    environment:
      - DSN=postgres://hydra:hydra@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      -
        type: bind
        source: ./hydra
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet
  
  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - intranet
    
  mailslurper:
    image: oryd/mailslurper:smtps-latest
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:
